name: Bandit security scanner

on:
  - push
  - pull_request

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: read
    steps:
      - name: Bandit security scanner
        uses: PyCQA/bandit-action@v1
        with:
          targets: "./src ./lsc_agent_eval ./lsc_eval"
